# Generated by Django 5.0.2 on 2024-02-27 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='recipe',
            new_name='recipe_id',
        ),
    ]
