# Generated by Django 5.0.2 on 2024-02-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='env_score',
            field=models.IntegerField(default=0),
        ),
    ]
