# Generated by Django 5.0.2 on 2024-02-20 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('foodle_score', models.IntegerField(default=0)),
                ('food_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_members', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foodle.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodle.group'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_title', models.CharField(max_length=200)),
                ('recipe_ingredients', models.CharField(max_length=200)),
                ('preparation', models.CharField(max_length=200)),
                ('prep_time', models.IntegerField(default=0)),
                ('serves_num', models.IntegerField(default=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodle.user')),
            ],
        ),
    ]
